#! /bin/sh
exit_version() {
	wr << ====; exit
$APP Version 2026.195
Copyright (c) 2020-2026 Guenther Brunthaler. All rights reserved.

This script is free software.
Distribution is permitted under the terms of the GPLv3.
====
}

exit_help() {
	wr << ====; echo; exit_version
$APP - Populate chroot-jails

Usage: $APP [ <options> ] <subdir> [ <executable_1> ... ]

$APP populates a directory <subdir> with executables and shared library
 dependencies taken from the live file system and copies them into a
 sub-directory structure which can then be used as chroot-jail for running the
 executables.

The executables and/or shared libraries are taken from the remaining
 arguments. If only <subdir> is specified, it is also used as <executable_1>.

The arguments specifying the executables and shared libraries are normally
 absolute path names.

If such an argument however does not contain a directory component separator
 ("/"), it will be searched via \$PATH and the resulting absolute pathname
 will be used as the effective argument.

After copying the specified executables and/or shared libraries into <subdir>
 using the same relative pathname as the absolute pathname of the source
 files, all additional shared libraries referenced by the copied files will
 also be copied into <subdir>. This recursively includes shared libraries
 referenced by the newly copied files as well.

All the specified executables/libraries must exist.

The <subdir> directory must not yet exist and will be created. However,
 options -u and -d can be specified to modify this requirement (see below).

Supported options:

-d: Delete <subdir> before populating the chroot jail. <subdir> must already
 exist.

-u: Update the already-existing <subdir>. <subdir> must exist. This allows to
 incrementally add more executables and/or shared libraries an
 already-existing and partially populated chroot-jail directory instead of
 specifying everything at once with a single invocation of $APP.

-h: Show this help and exit. -V: Show version information and exit.
====
}
APP=${0##*/}

set -e
cleanup() {
	rc=$?
	test "$TD" && rm -r -- "$TD"
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
trap cleanup 0
TD=
trap 'exit $?' TERM INT HUP QUIT PIPE

wr() {
	{
		unterminated=false
		while IFS= read -r line
		do
			test "${line%" "}" = "$line"
			test "${line#" "}" != "$line" && unterminated=false
			$unterminated && echo
			printf '%s' "$line"
			unterminated=true
		done
		$unterminated && echo
	} | fold -sw $LINEWIDTH
}
if
	test -t 0 && LINEWIDTH=`tput cols 2> /dev/null` \
	&& test "$LINEWIDTH"
then
	MAX=100
	test $LINEWIDTH -gt $MAX && LINEWIDTH=$MAX
else
	LINEWIDTH=${COLUMNS:-66}
fi

delete=false
update=false
while getopts udhV opt
do
	case $opt in
		u) update=true;;
		d) delete=true;;
		h) exit_help;;
		V) exit_version;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

case $# in
	0) exit_help;;
	1) set -- "$@" "$1"
esac

d=$1; d=${d%%/}
case $d in
	/*) d=/${d##/};;
	-*) d=./$d
esac
shift

n=$#
while test $n != 0
do
	if test -f "$1"
	then
		set -- "$@" "$1"
	else
		expr x"$1" : x'.*/' = 0 > /dev/null
		c=`command -v -- "$1"`
		test -f "$c"
		set -- "$@" "$c"
	fi
	shift
	n=`expr $n - 1 || :`
done

if $delete
then
	find -H "$d" -xdev -depth \
		-path "$d" \
		-o -type d -exec rmdir -- {} \; \
		-o -exec rm -- {} \;
elif $update
then
	test -d "$d"
else
	test ! -e "$d"
	mkdir -- "$d"
fi

TD=`mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`

write() {
	print '%s\n' "$*"
}

export LC_COLLATE=C

# Copy absolute file or symlink $f to rootjail at $d. If it is a symlink,
# check whether the referenced target also exists, or copy that target as
# well (recursively).
#
# Trashes: $f $t
copy_over() {
	while : 
	do
		t=$d/${f##/}
		mkdir -p -- "`dirname -- "$t"`"
		cp -Ppf -- "$f" "$t"
		test ! -L "$f" && break
		t=`readlink -- "$f"`
		case $t in
			/*) f=$t;;
			*) f=`dirname -- "$f"`/$t
		esac
	done
}

cwd=`pwd`
test -d "$cwd"
{
	for f
	do
		case $f in
			/*) ;;
			*) f=$cwd/$f
		esac
		test -f "$f" || test -L "$f" || exit
		copy_over
	done
}


find -H "$d" -xdev -type f -exec file -i -- {} + \
| awk -f /dev/fd/5 5<< 'EOF' > "$TD"/check
	$2 ~ "^application/.*(executable|sharedlib)" {
		print substr($1, 1, length($1) - 1)
	}
EOF

> "$TD"/checked
while test -s "$TD"/check
do
	while IFS= read -r f
	do
		ldd "$f" 2> /dev/null || :
	done < "$TD"/check \
	| awk '{$0= NF == 2 ? $1 : $3} $0 ~ "^/" {print}' | sort -u \
	| tee -- "$TD"/check_also \
	| while IFS= read -r f
	do
		copy_over
	done
	sort -u -o "$TD"/checked -- "$TD"/checked "$TD"/check
	comm -23 -- "$TD"/check_also "$TD"/checked > "$TD"/check
done
echo 'Success!'
