#!/bin/sh
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/sbin/delayed-shutdown $
# $Author: root(xtreme) $
# $Date: 2006-08-23T03:51:58.733319Z $
# $Revision: 212 $

nohup shutdown -hP +${1:-3} &> /dev/null &
