#! /bin/sh
# Display the current emerge status to a specified character device.
# Update display in periodic intervals.
# Also display as soon as emerge has finished.
# Goes into the background automatically using nohop.
# Never terminates; must be explicitly killed.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/sbin/emerge-tty-monitor $
# $Author: root(xvaio) $
# $Date: 2006-09-14T15:31:41.143795Z $
# $Revision: 295 $



die() {
	{
		echo "ERROR: $*"
		echo "Usage: $0 <output-char-device>"
	} >& 2
	exit 1
}


NDETACH=
while true; do
	case "$1" in
		--foreground) NDETACH=1;;
		*) break;;
	esac
	shift
done
OUT="$1"; shift
test -n "$OUT" || die "Missing output terminal specification!"
test -z "$1" || die "Excess arguments '$*'!"
test -c "$OUT" || die "'$OUT' is not a character device!"
test -w "$OUT" || die "No write permission for '$OUT'!"
if [ -z "$NDETACH" ]; then
	nohup "$0" --foreground "$OUT" > /dev/null 2>& 1 &
	echo "Background process $! has been started."
	echo "Use 'kill $!' to terminated it."
	exit
fi
while genlop -c; do
	sleep 60
	clear
done > "$OUT" 2> /dev/null
