#! /bin/sh
# Create a mount point directory, or set the conventional
# modes and owner for an existing one.
#
# Version 15.237
# (c) 2015 by Guenther Brunthaler.
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.


die() {
	echo "ERROR: $*" >& 2
	false; exit
}

while :
do
	if test ! -e "$1"
	then
		mkdir -p -- "$1" \
			|| die "Could not create mount point directory '$1'!"
	elif test ! -d "$1"
	then
		die "Mount point '$1' already exists and is not a directory!"
	fi
	chown nobody "$1" || die "Could not set owner for '$1'!"
	any=false
	for g in nogroup nobody
	do
		if chgrp $g "$1" 2> /dev/null
		then
			any=true
			break
		fi
	done
	$any || die "Could not set group for '$1'!"
	chmod ugo=,-st "$1" || die "Could not set permissions for '$1'!"
	echo "Mount point directory '$1' has successfully been set up!"
	shift
	test $# = 0 && break
done
