#! /bin/sh
MENU_FILE=/etc/xdg/openbox/menu.xml


die() {
	printf "ERROR: %s\n" "$*" >& 2
	false; exit
}


run() {
	"$@" && return
	die "Could not execute >>>$*<<< return code ${?}!"
}


system() {
	REPLY=`run "$@"` || exit
}


system dirname "$MENU_FILE"
run test -d "$REPLY"
run test -w "$REPLY"
run mmaker -c OpenBox3 > "$MENU_FILE"
echo "Success! Menu file has been written to '$MENU_FILE'!"
