#!/bin/sh
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/sbin/shutdown-after-emerge $
# $Author: root $
# $Date: 2007-08-01T14:35:29.737727Z $
# $Revision: 855 $


while wait-for-system-idle || wait-for-network-idle; do
	true
done
CONN=$HOME/bin/huiconnect
test -x "$CONN" && "$CONN"
exec delayed-shutdown
