#! /bin/sh
# Use ntpdate to synchronize the current system time
# with the machine "proxy" (typically defined in /etc/host).


case $1 in
	-*)
		echo "Usage: $0 [ <ntp_server> ]"
		exit
esac
# Checking for errors is not a good idea, as ntpdate returns 1
# if the stratum level is not low enough, which might always
# be the case for "proxy".
ntpdate -s -b -u "${1:-proxy}"
date
