#! /bin/sh
{
	src=/sys/class/thermal/thermal_zone0/temp
	if test -f "$src"
	then
		echo CPU `awk '{printf "%.1f\n", $1 / 1e3}' "$src"`
	fi
	src=/opt/vc/bin/vcgencmd
	if test -x "$src"
	then
		echo GPU `"$src" measure_temp | tr -cd '0-9.'`
	fi
} | sort -k2nr | awk '
	BEGIN {n= 0}

	{l[n]= $1; t[n++]= $2}

	END {
		if (n == 0) {
			print "(No supported temperature sources.)" \
				> "/dev/stderr"
		}
		else if (n == 1) print t[0]
		else {
			last= t[0];
			for (i= 1; i < n; ++i) {
				if (t[i] != last) {
					last= ""
					break
				}
			}
			if (last != "") print last
			else {
				for (i= 0; i < n; ++i) print l[i] " " t[i]
			}
		}
	}
'
