#! /bin/sh
# Add the sent/received bytes from the pppd syslog entries together for the
# current day and show the traffic sum.
#
# This script assumes a syslog format starting using YYYY-MM-DD format as the
# line prefix.
#
# If an argument is specified, it specifies an integral number of days and the
# sum will be calculated instead for the date that many day before the current
# day.
#
# Version 2017.168.1
# Copyright (c) 2017 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.
modem_ifc=ppp0

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
binary_units=0
while getopts pb opt
do
	case $opt in
		b) binary_units=1;;
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

date=`date +%s`
if test $# = 1
then
	expr x"$1" : x'[1-9][0-9]*$' \| x"$1" : x0 > /dev/null
	date=`expr $date - 60 \* 60 \* 24 \* $1`
	historic=true
else
	test $# = 0
	historic=false
fi
date=`date -d "@$date" +%Y-%m-%d`
decimal_point=.
eval `locale -k LC_NUMERIC | grep ^decimal_point=` 2> /dev/null || :
{
	logread | grep "^$date" | grep 'Sent.*received.*bytes' | sed '
		s/\([0-9]*\) bytes/<<\1>>/g
		s/[^<]*<<//
		s/[^0-9]\{1,\}/\n/g
	'
	$historic && exit
	p='X bytes[^0-9]*\([0-9]\{1,\}\)[^0-9].*'
	LC_ALL=C ifconfig "$modem_ifc" | sed 's/.*R'"$p"'T'"$p"'/\1 \2/; t; d'
} | sed '/^[^0-9]*$/d' | awk '
	BEGIN {s= 0}
	{s+= $0}
	END {
		bin= '"$binary_units"'
		split((bin ? "K" : "k") " M G T P E Z Y", u)
		for (i in u) u[i]= u[i] ((bin ? "i" : "") "B")
		u[i= 0]= "bytes"
		while (s >= (bin ? 1024 : 1000) && i + 1 in u) {
			++i; s/= bin ? 1024 : 1000
		}
		split(sprintf("%.2f", s), v, "[.]")
		v[3]= v[2] == 0 ? "" : v[2]
		v[2]= v[3] == "" ? "" : "."
		v[4]= " "; v[5]= u[i]
		s= ""
		for (i in v) s= s v[i]
		print s
	}
' | tr . "$decimal_point" | sed 's/^/'"$date: "'/'
