#! /bin/sh
# Archive the old version as a binary package before unmerging it.
# Accepts a list of package names or a list of files containing package names.


die() {
	echo "ERROR: $*" >& 2
	false; exit
}


run() {
	"$@" && return
	die "Could not execute command >>>$*<<< - return code ${?}!"
}


process() {
	echo "Backing up and uninstalling \"$1\"..."
	run quickpkg --ignore-default-opts --include-config=y \
		--include-unmodified-config=y "$1"
	CLEAN_DELAY=0 run emerge -C "$1"
	echo
}


usage() {
	die "Usage: ${0##*/} <package> ... | --list [ - | <package-list> ] ..."
}


test $# = 0 && usage
if test x"$1" != x"--list"
then
	for PACKAGE
	do
		process "$PACKAGE"
	done
else
	shift
	for PACKAGELIST
	do
		test x"$PACKAGELIST" = x- && PACKAGELIST=/dev/stdin
		test -f "$PACKAGELIST" \
			|| test -p "$PACKAGELIST" || usage
		for PACKAGE in `IFS= cat "$PACKAGELIST"`
		do
			process "$PACKAGE"
		done
	done
fi
