#! /bin/sh
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/sbin/update-portage-from $
# $Author: root(xvaio) $
# $Date: 2006-10-31T06:34:28.304671Z $
# $Revision: 373 $
#
# Use rysnc via SSH to synchronize the local portage tree
# from the portage tree on machine $1, except for the
# distfiles subdirectory.
#
# Then all new files in the distfiles subdirectory on the
# machine $1 are mirrored to the local machine. (Files
# which only exist in the local distfiles directory
# are left alone.)
#
# Written in 2006 by Guenther Brunthaler


NICENESS="10"


die() {
	echo "ERROR: $*" >& 2
	exit 1
}


do_run() {
	"$@" || die "Failed: >>>$*<<<!"
}


do_nice() {
	do_run nice "-$NICENESS" "$@"
}


do_rsync() {
	do_nice rsync \
		--rsh='ssh -o Compression=no' \
		--archive --safe-links \
		--human-readable --human-readable --stats \
		"$@"
}


ONLYDIST=
while true; do
	case "$1" in
		--only-distfiles | -D) ONLYDIST=1;;
		--* | -*) die "Unsupported option '$1'!";;
		--) shift; break;;
		*) break;;
	esac
	shift
done
RHOST="$1"
test "`whoami`" = "root" || die "Must be run be root!"
test -n "$RHOST" || die "Usage: $0 <host>"
ssh "$RHOST" true \
	|| die "The SSH connection does not work!" \
		"(Forgot to set up ssh-agent?)"
if [ -z "$ONLYDIST" ]; then
	do_rsync --compress --whole-file --delete-after \
		--exclude "/distfiles/" --exclude "/packages/" \
		--exclude "/local/" \
		"$RHOST:/usr/portage/" "/usr/portage/"
fi
do_rsync --update \
	"$RHOST:/usr/portage/distfiles/" "/usr/portage/distfiles/"
if [ -z "$ONLYDIST" ]; then
	emerge --metadata
	which eupdatedb > /dev/null 2>& 1 && eupdatedb || true
fi
