#!/bin/sh
# Launch the console server, but only if the support service is running.
#
# $HeadURL: /caches/xsvn/uxadm/trunk/usr/local/sbin/vmware-authd-proxy $
# $Author: root $
# $Date: 2007-06-01T00:18:51.336924Z $
# $Revision: 777 $

CONTROL_SCRIPT="/etc/init.d/vmware-authd"
ACTUAL_SERVER="/opt/vmware/server/sbin/vmware-authd"

if "$CONTROL_SCRIPT" --quiet status &> /dev/null < /dev/null; then
	logger -p daemon.info -t vmware-server "connection forwarded to running VMware services"
	exec "$ACTUAL_SERVER"
fi
logger -p daemon.err -t vmware-authd-proxy "rejected attempt to access the stopped VMware services"
