#! /bin/sh
# Accept any number of connections (in sequence) via SSH on $PORT.

PORT=5900
#
DRY_RUN=
while getopts n OPT
do
	case $OPT in
		n) DRY_RUN=Y;;
		*) false; exit
	esac
done
set -- `ps -A -o cmd | grep ^/usr/bin/X `
AUTH=
DISP=
while test $# != 0
do
	case $1 in
		*-auth) AUTH=$2;;
		:[0-9]*) DISP=$1
	esac
	shift
done
set -- x11vnc -display "$DISP" -listen localhost -autoport "$PORT"
test -n "$AUTH" && set -- "$@" -auth "$AUTH"
set -- "$@" -forever
if test -n "$DRY_RUN"
then
	echo "SIMULATION: $*"
	exit
fi
exec "$@"
